import { Permission } from '../types/partnerPermission';

/**
 * TEMPORARY static mock of the `user/services/partner-initial-sidebar` response,
 * used while the backend flattening is not yet implemented.
 *
 * Difference from the current API shape: the `"More Services"` wrapper node is
 * removed and its sub-services are promoted to **top-level** entries (each marked
 * `enableMoreService: true`). Every service also carries an `icon` (served from a
 * static CDN) and an explicit `enableMoreService` flag (defaults to `false`).
 * Remove this file and switch back to `useUpdateRoles().permissionData` once the
 * backend returns the flattened shape.
 */
const ICON_CDN = 'https://cdn.peko.one/service-icons';

export const staticPartnerPermissions: Permission[] = [
    {
        label: 'Dashboard',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/dashboard.svg`,
    },
    {
        label: 'Mobile Recharge & Bills',
        hasAccess: false,
        enableMoreService: false,
        icon: `${ICON_CDN}/mobile-recharge-and-bills.svg`,
        subServices: [
            { label: 'Prepaid', hasAccess: false },
            { label: 'Postpaid', hasAccess: false },
            { label: 'Test', hasAccess: false },
        ],
    },
    {
        label: 'Utility Payments',
        hasAccess: false,
        enableMoreService: false,
        icon: `${ICON_CDN}/utility-payments.svg`,
        subServices: [
            { label: 'Electricity Bill', hasAccess: false },
            { label: 'Broadband Bill', hasAccess: false },
            { label: 'LPG Cylinder', hasAccess: false },
            { label: 'Water Bill', hasAccess: false },
            { label: 'Landline Bill', hasAccess: false },
            { label: 'Piped Gas', hasAccess: false },
            { label: 'Education Fee', hasAccess: false },
            { label: 'Insurance', hasAccess: false },
            { label: 'Cable Recharge', hasAccess: false },
            { label: 'DTH Recharge', hasAccess: false },
            { label: 'FASTag Recharge', hasAccess: false },
            { label: 'Traffic Challan', hasAccess: false },
            { label: 'Clubs & Associations', hasAccess: false },
            { label: 'Hospital & Pathology', hasAccess: false },
            { label: 'Subscription', hasAccess: false },
            { label: 'NCMC', hasAccess: false },
            { label: 'NPS', hasAccess: false },
            { label: 'Prepaid Meter', hasAccess: false },
            { label: 'Life Insurance', hasAccess: false },
            { label: 'Bike Insurance', hasAccess: false },
            { label: 'Car Insurance', hasAccess: false },
            { label: 'Credit Card Payment', hasAccess: false },
            { label: 'Loan Repayment', hasAccess: false },
            { label: 'Municipal Taxes', hasAccess: false },
            { label: 'Municipal Services', hasAccess: false },
            { label: 'Recurring Deposite', hasAccess: false },
            { label: 'Rental', hasAccess: false },
            { label: 'Donations', hasAccess: false },
            { label: 'Housing Society', hasAccess: false },
            { label: 'Complaint Registration', hasAccess: false },
        ],
    },
    {
        label: 'Corporate Travel',
        hasAccess: false,
        enableMoreService: false,
        icon: `${ICON_CDN}/corporate-travel.svg`,
        subServices: [
            { label: 'airline', hasAccess: false },
            { label: 'hotels', hasAccess: false },
            { label: 'eSIM', hasAccess: false },
        ],
    },
    {
        label: 'Payroll',
        accessKey: 'peko_payroll',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/payroll.svg`,
    },
    {
        label: 'Office Supplies',
        accessKey: 'ecommerce',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/office-supplies.svg`,
    },
    {
        label: 'Domain & Hosting',
        accessKey: 'domain_and_hosting',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/domain-and-hosting.svg`,
    },
    {
        label: 'Turbo',
        accessKey: 'peko_garage',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/turbo.svg`,
    },
    {
        label: 'eSign',
        accessKey: 'signDrive_eSign',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/esign.svg`,
    },
    {
        label: 'Verification Suite',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/verification-suite.svg`,
    },
    {
        label: 'Peko Wallet',
        accessKey: 'peko_wallet',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/peko-wallet.svg`,
    },
    {
        label: 'Business Registration',
        accessKey: 'business_registration',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/business-registration.svg`,
    },
    {
        label: 'Global Business Setup',
        accessKey: 'global_business_setup',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/global-business-setup.svg`,
    },
    {
        label: 'Compliance',
        accessKey: 'compliance',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/compliance.svg`,
    },
    {
        label: 'Procure',
        accessKey: 'procure',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/procure.svg`,
    },
    {
        label: 'Payouts',
        accessKey: 'vendor_payouts',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/payouts.svg`,
    },
    {
        label: 'Payment Links',
        accessKey: 'quick_links',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/payment-links.svg`,
    },
    {
        label: 'Document Attestation',
        accessKey: 'document_attestation',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/document-attestation.svg`,
    },
    {
        label: 'Business Docs',
        accessKey: 'edocs',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/business-docs.svg`,
    },
    {
        label: 'Office Address',
        accessKey: 'workspace',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/office-address.svg`,
    },
    {
        label: 'Soundbox',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/soundbox.svg`,
    },
    {
        label: 'Paytm BPOS',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/paytm-bpos.svg`,
    },
    {
        label: 'License Renewal',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/license-renewal.svg`,
    },
    {
        label: 'Works',
        accessKey: 'peko_works',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/works.svg`,
    },
    {
        label: 'Zero Carbon',
        accessKey: 'carbon_footprint',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/zero-carbon.svg`,
    },
    {
        label: 'Connect',
        accessKey: 'peko_connect',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/connect.svg`,
    },
    {
        label: 'ESR',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/esr.svg`,
    },
    {
        label: 'Hike',
        accessKey: 'hike_service',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/hike.svg`,
    },
    {
        label: 'Business Emails',
        accessKey: 'email_domain_service',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/business-emails.svg`,
    },
    {
        label: 'Government Services',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/government-services.svg`,
    },
    {
        label: 'Logistics',
        accessKey: 'shipment_services',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/logistics.svg`,
    },
    {
        label: 'Legal Service',
        accessKey: 'legal_service',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/legal-service.svg`,
    },
    {
        label: 'Softwares',
        accessKey: 'subscription_payments',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/softwares.svg`,
    },
    {
        label: 'Gift Cards',
        accessKey: 'quickcilver',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/gift-cards.svg`,
    },
    {
        label: 'Marketplace',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/marketplace.svg`,
    },
    {
        label: 'Tax & More',
        hasAccess: false,
        enableMoreService: false,
        icon: `${ICON_CDN}/tax-and-more.svg`,
        subServices: [
            { label: 'GST Filing', hasAccess: false },
            { label: 'TDS Filing', hasAccess: false },
        ],
    },
    {
        label: 'Invoicing',
        accessKey: 'invoices',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/invoicing.svg`,
    },
    {
        label: 'Insurance',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/insurance.svg`,
    },
    {
        label: 'WhatsApp for Business',
        accessKey: 'whatsApp_for_busines',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/whatsapp-for-business.svg`,
    },
    {
        label: 'Corporate Cards',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/corporate-cards.svg`,
    },
    {
        label: 'Accounting',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/accounting.svg`,
    },
    {
        label: 'Hub',
        accessKey: 'pekoCloud',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/hub.svg`,
    },
    {
        label: 'Sales',
        accessKey: 'sales',
        hasAccess: false,
        subServices: [],
        enableMoreService: false,
        icon: `${ICON_CDN}/sales.svg`,
    },
    {
        label: 'Reports',
        hasAccess: false,
        enableMoreService: false,
        icon: `${ICON_CDN}/reports.svg`,
        subServices: [
            { label: 'Transactions', hasAccess: false },
            { label: 'Cashbacks', hasAccess: false },
            { label: 'Scheduling Reports', hasAccess: false },
            { label: 'Subscription Transactions', hasAccess: false },
        ],
    },
    {
        label: 'Need Help',
        hasAccess: false,
        enableMoreService: false,
        icon: `${ICON_CDN}/need-help.svg`,
        subServices: [
            { label: 'Contact Us', hasAccess: false },
            { label: 'Tickets', hasAccess: false },
            { label: 'Frequently Asked Questions', hasAccess: false },
        ],
    },
    {
        label: 'Settings',
        hasAccess: false,
        enableMoreService: false,
        icon: `${ICON_CDN}/settings.svg`,
        subServices: [
            { label: 'User Management', hasAccess: false },
            { label: 'Billing & Saved Cards', hasAccess: false },
            { label: 'Subscription Plans', hasAccess: false },
            { label: 'Security', hasAccess: false },
            { label: 'Connected Apps', hasAccess: false },
        ],
    },
];

export default staticPartnerPermissions;
