/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                fontSubBlack: '#3E3E3E',
                lightGreen: '#EFFFE8',
                successGreen: '#43AA00',
                bgLightOrange: '#FFFAF8',
                bgLightPurple: '#FFF6FF',
                bgLime: '#F9FAF6',
                bgIconCard: '#FFF7F6',
                borderPrimaryLight: '#FFE4E4',
                titleText: '#8B8B8B',
                valueText: '#171717',
                iconRed: '#EA3639',
                iconBgRed: '#FFF7F7',
                bgLightYellow: 'rgba(255, 252, 242, 1)',
                bgLightBlue: '#F0FAFF',
                textGreen: '#26A411',
                textGrey: '#9C9DA1',
                titleDescription: '#B2B2B2',
                cardHTitleText: '#7b7b7b',
                bgResultCard: ' #F9F9F9',
                impactReportCardBg: '#FAFAFA',
                textRed: '#FF3A3A',
                errorTextRed: '#FF4D4F',
                chatCardBg: '#F9F9F9',
                chatBg: '#FF6A6A',
                contactUsBg: '#FAFAFA',
                faqText: '#4F5D64',
                bgGray: '#F7F9FB',
                textGreenTitle: '#25A311',
                bgSkin: '#FFF6F6',
                bgOrangeShade: '#FFF9F0',
                brandColor: '#FF3A3A',
                bgOrange: '#FF4D4F',
                bgOrange2: '#FF3A3A',
                neutralGray500: '#D9D9D9',
                textBlack: '#000',
                textGray: '#717171',
                textWhitesmoke: '#D1D1D1',
                textDimGray: '#2D2D2D',
                textDimGreen: '#26A411',
                bgDodgerblue: '#1890FF',
                textWhite: '#fff',
                textLime: '#05BE63',
                textMoroon: '#AB1E1E',
                themeSelectorOne: '#FBE7E7',
                themeSelectorTwo: '#22075E',
                themeSelectorThree: '#002766',
                themeSelectorFour: '#A8071A',
                customBorderColor: '#E1E7EE',
                bgLightGray: '#F7F9FB',
                textDarkGray: '#595959',
                borderGray: '#E4E7EC',
                bgGrayF9: '#F9F9F9',
                textLightGray: '#7B7B7B',
                bgGrayCard: '#F9F9F9',
                textYellow: '#DEC300',
                textOrange: '#FF910F',
                textGreenLight: '#05BE63',
                textC1B: '#575757',
                bgF7F9Fb: '#F7F9FB',
                bgSoundbox: '#F7F9FB',
                bgLightblue: '#F9F9F9',
                textGreyColor: '#8C8C8C',
                tagColor: '#FFF7F6',
                bgGold: '#FFC700',
                textBtnGray: '#4A4B57',
                skeltonGray: '#F0F0F0',
                listBg: '#f5f5f5',
                textLightGreen: '#72DAA7',
                textDisabledGray: '#808080',
                neutriliseVal: '#1D493E',
                navTextColor: '#212121',
                bgLightGreen: '#E4FFE8',
                magnolia: '#F9F4FF',
                seashell: '#FFF6F2',
                bgBluish: '#E6FFF6',
                bgMud: '#F5FFD5',
                textDarkGreen: '#008242',
                textInfoGrey: '#B1B1B1',
                productText: '#A2A2A2',
                bgGreenPayment: '#59CE4E',
                textBlackGray: '#2E2E2E',
                bgLightPink: '#FFF4F3',
                bgBlue: '#E3F5FF',
                bgOceanBlue: '#EAFFF7',
                bgOrangeYellow: '#FFF4CD',
                greyBlack: '#F7F7F7',
                signInText: '#424242',
                regText: '#FFFCEC',
                bgLightGrayFD: '#FDFCFF',
                textLightRed: '#FF4F4F',
                textHeadings: '#1e293b',
                textBody: '#475569',
                textGreyLight: '#828282',
                vidoCallGreen: '#03B94D',
                audioCallGreen: '#38D58A',
                declineCallRed: '#FF0000',
                lightRed: '#FF4F4F',
                greyTitle: '#383838',
                esimInfoCardYellow: '#FFFEDB',
                esimInfoCardPink: '#FFF3F3',
                esimInfoCardPurple: '#FCF9FF',
                bgGrayF8: '#F8F8F8',
                savingsTagGreen: '#05BE63',
                savingsTagLightBg: '#ECFDF5',
                savingsTagLightText: '#43B75D',
                tableHeaderText: '#475156',
                tableHeaderBg: '#FAFAFA',
                borderCard: '#E6EAF0',
                borderDivider: '#F0F2F5',
                textPrimary: '#121212',
                bgLavender: '#FAF4FF',
                bgLightRed: '#FEF2F2',
                // ── Semantic / Insights design tokens (from Figma design system) ──
                success: { DEFAULT: '#43B75D', surface: '#ECFDF5', border: '#81CF92' },
                warning: { DEFAULT: '#F59E0B', surface: '#FFFBEB', border: '#FCD34D' },
                danger: { DEFAULT: '#FF4F4F', surface: '#FEF2F2', border: '#FCA5A5' },
                ink: '#1E293B', // headings
                bodyText: '#475569', // body copy
                muted: '#667085', // secondary/labels
                titleMuted: '#8B8B8B', // section titles
                surfaceGray: '#F8FAFC',
                borderSubtle: '#E4E4E7',
                borderStrong: '#CBD5E1',
                bgLightRose: '#FFFCFC',
                borderLightRose: '#FFEAEA',
            },
            fontSize: {
                custom: '15px',
                lightGray: '#C7C7C7',
            },
            screens: {
                // to match with antD screen sizes
                xs: '0px', // >=0
                xs375: '375px', // >=375
                sm: '576px', // >=576
                md: '768px', // >=768
                lg: '992px', // >=992
                xl: '1200px', // >=1200
                xxl: '1600px', // >=1600
            },
            fontWeight: {
                'extra-light': 300,
                regular: 400,
                'extra-bold': 800,
            },
            gridTemplateColumns: {
                transactions:
                    '2.75rem minmax(5rem,0.7fr) minmax(13rem,2.2fr) minmax(8.5rem,1.2fr) minmax(6.5rem,0.9fr) minmax(5rem,0.75fr) minmax(6.5rem,0.85fr) minmax(7.5rem,0.95fr) minmax(8.5rem,1fr)',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: 0, transform: 'translateY(4px)' },
                    '100%': { opacity: 1, transform: 'translateY(0)' },
                },
                fadeInOpacity: {
                    '0%': { opacity: 0 },
                    '100%': { opacity: 1 },
                },
                progressIndeterminate: {
                    '0%': { transform: 'translateX(-100%)' },
                    '100%': { transform: 'translateX(400%)' },
                },
                confettiFall: {
                    '0%': { transform: 'translateY(-10px) rotate(0deg)', opacity: 0 },
                    '15%': { opacity: 1 },
                    '100%': { transform: 'translateY(90px) rotate(200deg)', opacity: 0 },
                },
                popIn: {
                    '0%': { transform: 'scale(0.9)', opacity: 0 },
                    '100%': { transform: 'scale(1)', opacity: 1 },
                },
            },
            animation: {
                'fade-in': 'fadeIn 0.25s ease-out both',
                'fade-in-opacity': 'fadeInOpacity 0.3s ease-out both',
                'progress-indeterminate': 'progressIndeterminate 1.2s ease-in-out infinite',
                'confetti-fall': 'confettiFall 1.1s ease-in forwards',
                'pop-in': 'popIn 0.3s cubic-bezier(0.34, 1.56, 0.64, 1) both',
            },
        },
        fontFamily: {
            helvetica: ['Helvetica', 'Arial', 'sans-serif'],
            roboto: ['Roboto', 'sans-serif'],
        },
    },
    plugins: [],
};
