// ----------------------------------------------------------------------

const ROOTS = {
    AUTH: '/auth',
    ADMIN: '/admin',
    ECOM: '/manager',
    SYSYTEM_USER: '/system-user',
    EMPLOYEE: '/employee',
};

// ----------------------------------------------------------------------

export const paths = {
    // AUTH
    auth: {
        jwt: {
            login: `${ROOTS.AUTH}/login`,
            consent: `${ROOTS.AUTH}/consent`,
            register: `${ROOTS.AUTH}/register`,
        },
        socialLogin: `/social`,
        socialError: `/error`,
        ssoLogin: `/sso/login`,
        resetPassword: `/reset-password`,
        passwordSuccess: '/password-update-success',
        verifyEmail: '/verify-email',
        setPassword: `/set-password`,
    },
    // DASHBOARD
    dashboard: {
        home: '/dashboard',
        mobileRecharge: '/mobile-recharge-&-bills',
        billPayments: '/utility-payments',
        corporateTravel: '/corporate-travel',
        payroll: '/payroll',
        payout: '/payouts',
        payoutAll: '/payouts/all-payouts',
        payoutBillPayout: '/payouts/bill-payout',
        payoutRent: '/payouts/rent',
        payoutVendorPayments: '/payouts/vendor-payments',
        officeSupplies: '/office-supplies',
        productDetails: '/office-supplies/product-details/:id',
        cartPage: '/office-supplies/carts',
        orderPlaced: '/office-supplies/order-placed',
        orderDetails: '/office-supplies/order-details',
        orderDetailsMobile: '/office-supplies/order-details-mobile/:id',
        cancelledDetails: '/office-supplies/cancelled-details',
        returnedDetails: '/office-supplies/returned-details',
        orderHistory: '/office-supples/order-history',
        changeAddress: '/office-supplies/change-address',
        subscriptions: '/softwares',
        logistics: '/logistics',
        giftCards: '/gift-cards',
        connect: '/marketplace',
        works: '/works',
        invoicing: '/invoicing',
        zeroCarbon: '/zero-carbon',
        tax: '/tax',
        taxMore: '/tax-more',
        accounting: '/accounting',
        moreServices: '/more-services',
        reports: '/reports',
        needHelp: '/need-help',
        profile: '/profile',
        businessDocs: '/bussiness-docs',
        whatsappForBusiness: '/whatsApp-for-business',
        ecommerce: '/peko-commerce',
        eSign: '/eSign',
        licenseRenewal: '/license-renewal',
        officeAddress: 'office-address',
        hotels: '/hotels',
        insurance: '/insurance',
        soundBox: '/sound-box',
        paytmBpos: '/paytm-bpos',
        vendorPayouts: 'vendor-payouts',
        corporateCard: 'corporate-cards',
        paymentLinks: '/payment-links',
        payments: '/payments',
        notifications: '/notifications',
        pekoCredit: '/peko-credit',
        pekoCloud: '/hub',
        plans: '/plans',
        serviceNotAvailable: '/service-not-available',
        settings: '/settings',
        emailDomain: 'business-emails',
        pekoConnect: '/connect',
        hike: 'hike',
        turbo: '/turbo',
        pekoWallet: 'peko-wallet',
        verificationSuite: '/verification-suite',
        domainHosting: '/domain-&-hosting',
        businessRegistration: '/business-registration',
        globalBusinessSetup: '/global-business-setup',
        procure: '/procure',
        governmentServices: '/government-services',
        sales: '/sales',
        legalService: '/legal-service',
        compliance: '/compliance',
    },
    legalService: {
        index: 'legal-service',
        browseTemplates: 'browse-templates',
        document: 'document/:templateId',
        sendForSignature: 'document/:templateId/send-for-esign',
        documentDetail: 'document/:templateId/details',
        personalDocument: 'personal-document/:templateId',
    },
    compliance: {
        index: '/more-services/compliance',
        dashboard: 'dashboard',
        health: 'dashboard/health',
        detail: 'dashboard/health/detail/:id',
        documents: 'dashboard/documents',
        myCompliances: 'dashboard/my-compliances',
        tracker: 'dashboard/my-compliances/tracker/:id',
        completedView: 'dashboard/my-compliances/completed/:id',
        onboarding: 'onboarding',
        landing: 'landing',
        incorporation: 'incorporation',
        companyIdentify: 'company-identify',
        companyDetails: 'company-details',
        confirmCompanyDetails: 'confirm-company-details',
    },
    taxMore: {
        index: 'tax-more',
        kycVerifyPan: 'kyc/verify-pan',
        kycChooseBusiness: 'kyc/choose-business',
        kycFinalise: 'kyc/finalise',
        gstFiling: 'gst-filing',
        uploadSalesInvoices: 'gst-filing/upload-invoices',
        fileGstr1: 'gst-filing/file-gstr1',
        ims: 'ims',
        gstr2b: 'gstr-2b',
        fileGstr3b: 'gst-filing/file-gstr3b',
        gstLedger: 'gst-ledger',
        supplierCompliance: 'supplier-compliance',
        gstinLookup: 'gstin-lookup',
        filingHistory: 'filing-history',
        fileGstr9: 'gst-filing/file-gstr9',
    },
    sales: {
        index: 'sales',
        customerLeads: 'customer-leads',
        customersBulkUpload: 'bulk-upload',
        invoices: 'invoices',
        createInvoice: 'create-invoice',
        invoicedetails: 'invoice-details/:id',
        editInvoice: 'edit-invoice/:id',
        salesOrders: 'sales-orders',
        salesOrderDetails: 'sales-order-details/:id',
        createSalesOrder: 'create-sales-order',
        editSalesOrder: 'edit-sales-order/:id',
        quotations: 'quotations',
        quotationDetails: 'quotation-details/:id',
        createQuotation: 'create-quotation',
        editQuotation: 'edit-quotation/:id',
        payment: 'payment',
        agreements: 'agreements',
        agreementDetail: 'agreements/:id',
        createAgreement: 'agreements/create',
        editAgreement: 'agreements/:id/edit',
    },
    zeroCarbon: {
        id: '/:id',
        index: 'zero-carbon',
        carbonCalculator: 'carbon-calculator',
        result: 'result',
        projectDetails: 'project-details',
        neutralize: 'neutralize',
        buyCredits: 'buy-Credits',
        impactReport: 'impact-report',
        projectListing: 'project-listing',
        whyAct: 'why-act',
        transactions: 'transactions',
        payment: 'payment',
        paymentStatus: 'payment-status',
        shareImpact: 'share-impact',
    },
    connect: {
        index: 'marketplace',
        details: 'details/:id',
        success: 'success',
        failed: 'failed',
    },
    needHelp: {
        index: 'need-help',
        faq: 'frequently-asked-questions',
    },
    pekoConnect: {
        index: 'connect',
        videoCall: 'video-call',
    },
    reports: {
        index: 'reports',
        faq: 'faq',
        addOns: 'add-ons',
    },
    paymentLinks: {
        index: 'payment-links',
        CreatePayment: 'create',
        ENachMandates: 'enach-mandates',
        Transactions: 'transactions',
        TransactionDetail: 'transactions/transaction-details',
        VirtualAccountStatement: 'virtual-account-statement',
    },
    paymentLinkPublicSuccess: '/payment-link/success',
    eNachMandatePublicSuccess: '/enach-mandate/success',
    rfqPublicSubmit: '/procure/proposals/submit/:token',
    ondcStaticTerms: '/ondc/static-terms',
    poPublicAcknowledge: '/procure/po/acknowledge/:token',
    subscriptions: {
        index: 'softwares',
        id: '/:id',
        details: 'details',
        companyDetails: 'purchase',
        payment: 'payment',
        success: 'success',
        failed: 'failed',
        orderHistory: 'order-history',
    },
    softwares: {
        index: 'softwares',
        category: 'category',
        product: 'product',
        findSoftware: 'find-software',
        success: 'success',
        viewPlans: 'view-plans',
        orderHistory: 'order-history',
        managePlan: 'manage-plan',
        searchResults: 'search-results',
        getAssistanceSuccess: 'get-assistance-success',
    },
    businessDocs: {
        index: 'business-docs',
        category: 'category',
    },
    telecomPayments: {
        index: 'mobile-recharge-&-bills',
        prepaid: 'prepaid',
        postpaid: 'postpaid',
        test: 'test',
    },
    billPayments: {
        index: 'utility-payments',
        electricity: 'electricity-bill',
        broadband: 'broadband-bill',
        lpg: 'lpg-cylinder',
        water: 'water-bill',
        landline: 'landline-bill',
        pipedGas: 'piped-gas',
        education: 'education-fee',
        bulkUpload: 'bulkupload',
        bulkPayment: 'bulk-payment',
        creditCard: 'credit-card-payment',
        cable: 'cable-recharge',
        dth: 'dth-recharge',
        fastag: 'fastag-recharge',
        loanRepayment: 'loan-repayment',
        municipalTaxes: 'municipal-taxes',
        municipalServices: 'municipal-services',
        recurringDeposite: 'recurring-deposite',
        rental: 'rental',
        donations: 'donations',
        Insurance: 'insurance',
        bikeInsurance: 'bike-insurance',
        carInsurance: 'car-insurance',
        lifeInsurance: 'life-insurance',
        clubs: 'clubs-associations',
        hospital: 'hospital-pathology',
        housingSociety: 'housing-society',
        subscription: 'subscription',
        ncmc: 'ncmc',
        nps: 'nps',
        prepaidMeter: 'prepaid-meter',
        challan: 'traffic-challan',
        challanOrders: 'orders',
        complaintRegistration: 'complaint-registration',
        ComplaintRegister: 'register-complaint',
        success: 'success',
    },
    payments: {
        index: 'payments',
        paymentsuccess: 'payment-success',
        paymentFailure: 'payment-failure',
        paymentPending: 'payment-pending',
        subscriptionPending: 'subscription-pending',
        ccavenueProcessing: 'ccavenue-processing',
    },
    hotels: {
        index: 'hotels',
        details: 'hotel-listing',
        hotelView: 'hotel-details',
        bookings: 'booking-summary',
        manageBookings: 'manage-bookings',
        userDetails: 'guest-information',
        reviewPayment: 'payment-review',
    },
    accounting: {
        index: 'accounting',
        transactions: 'transactions',
        financialStatements: 'financial-statements',
        profitLoss: 'financial-statements/profit-loss',
        balanceSheet: 'financial-statements/balance-sheet',
        cashFlow: 'financial-statements/cash-flow',
        expenseStatement: 'financial-statements/expense-statement',
        revenueStatement: 'financial-statements/revenue-statement',
        gstSummary: 'financial-statements/gst-summary',
        accountsReceivable: 'financial-statements/accounts-receivable',
        accountsPayable: 'financial-statements/accounts-payable',
        insights: 'insights',
    },
    officeSupplies: {
        index: 'office-supplies',
        id: 'id',
        productDetails: 'product-details',
        products: 'products',
        cartPage: 'cart',
        checkout: 'cart/checkout',
        // Landing the shared /payments screen redirects to (slice `successPath`)
        // once Cashfree has captured — it runs the ONDC confirm that places the order.
        placingOrder: 'placing-order',
        orderPlaced: 'order-placed',
        orderDetails: 'order-details',
        orderHistory: 'order-history',
    },
    bus: {
        index: 'bus',
        results: 'search-results',
        seatSelection: 'seat-selection-and-bus-details',
        traveller: 'traveller-details',
        review: 'review-booking',
        manageBookings: 'manage-bookings',
        bookingConfirmed: 'booking-confirmed',
    },
    airline: {
        index: 'airline',
        results: 'flight-details',
        details: 'passenger-details',
        summary: 'summary',
        manage: 'manage-bookings',
        bookingDetails: 'modify-or-cancel-booking',
        cancelDetails: 'cancel',
        cancelSuccess: 'cancellation-received',
    },
    logistics: {
        index: 'logistics',
        details: 'shipment-details',
        payment: 'payment',
        paymentStatus: 'payment-status',
        track: 'track',
        trackOrderDetails: 'track-order-details',
        orderHistory: 'order-history',
        orderDetails: 'order-view',
        returnShipment: 'return-shipment',
        addressBook: 'address-book',
    },
    // logistics: {
    //     index: 'logistics',
    //     details: 'shipment-details',
    //     payment: 'payment',
    //     paymentStatus: 'payment-status',
    //     track: 'track',
    //     orderHistory: 'order-history',
    //     orderDetails: 'order-view',
    // },
    visa: {
        index: 'visa',
        results: 'visa-results',
        travellerDetails: 'traveller-details',
        visaPayment: 'visa-payment',
        visaSuccess: 'visa-success',
        visaTracking: 'visa-tracking',
        visaTrackingDetail: 'visa-tracking/:orderNumber',
        manageBookings: 'manage-bookings',
    },
    esim: {
        index: 'eSIM',
        packages: 'packages',
        details: 'package-details',
        orders: 'orders',
        esimDetails: 'package-details',
        ReplacePackage: 'replace-package',
        topup: 'top-up-package-details',
        howEsim: 'how-it-works',
    },
    eSign: {
        index: 'eSign',
        uploadPage: 'upload',
        viewPage: 'view',
        historyPage: 'status',
        successPage: 'success',
        settings: 'settings',
    },
    officeAddress: {
        index: 'office-address',
        plans: 'plans',
        basic: 'basic',
        premium: 'premium',
        flexi: 'flexi',
        orderhistory: 'order-history',
    },
    hike: {
        index: 'hike',
        purchasePage: 'purchase-hike',
        checkoutPage: 'purchase-details',
        historyPage: 'history',
        successPage: 'success',
    },
    works: {
        index: 'works',
        detail: 'details',
        id: ':id',
        purchased: 'purchased',
        purchase: 'purchase',
        planId: ':planId',
        orderHistory: 'order-history',
        orderDetails: 'order-details',
    },
    officeAddresses: {
        details: 'details',
        basic: 'basic',
        premium: 'premium',
        flexi: 'flexi',
    },
    whatsappForBusiness: {
        index: 'whatsApp-for-business',
        planDetails: 'plan-details',
        MyProjects: 'my-projects',
        reviewOrder: 'subscription',
        paymentsuccess: 'payment-success',
        successPage: 'success',
    },
    emailDomain: {
        index: 'business-emails',
        detailsPage: ':detail',
        historyPage: 'order-history',
    },
    soundbox: {
        orderDetails: 'order-details',
        details: 'details',
    },
    paytmBpos: {
        index: 'paytm-bpos',
        request: 'request',
        submitted: 'request-submitted',
        orderHistory: 'order-history',
    },
    payment: {
        success: 'success',
        failed: 'failed',
    },
    invoice: {
        index: 'invoicing',
        kyb: 'kyb',
        kybDocumentPage: 'documents',
        kybVerification: 'kyb-verification',
        kybeSign: 'eSign',
        upload: 'upload-invoice',
        create: 'create-invoice',
        edit: 'edit-invoice/:id',
        customers: 'customers',
        customersBulkUpload: 'bulk-upload',
        invoicedetails: 'invoice-details/:id',
        invoicehistory: 'track-invoice',
        trackDetails: 'invoice-history-details',
        guidelines: 'guidelines',
        success: 'success',
        paymentLinks: 'payment-links',
        orderHistory: 'order-history',
        allInvoice: 'all-invoices',
        eInvoicingSignIn: 'e-invoicing-sign-in',
        eInvoicing: 'e-invoicing',
        eInvoicingAll: 'e-invoicing/all-e-invoices',
        convertToEInvoice: 'e-invoicing/convert-to-einvoice',
        generateIrn: 'e-invoicing/generate-irn',
        eInvoiceDetails: 'e-invoicing/e-invoice-details/:id',
        eInvoicingWaybill: 'e-invoicing/e-waybill',
        eInvoicingGstinLookup: 'e-invoicing/gstin-lookup',
        eInvoicingManageSubscription: 'e-invoicing/manage-subscription',
        catalog: 'catalog',
        creditNotes: 'credit-notes',
        creditNoteCreate: 'credit-notes/create',
        creditNotePreview: 'credit-notes/preview',
        creditNoteDetails: 'credit-notes/:id',
        receipts: 'payments-received',
        templates: 'templates',
        recurring: 'recurring-invoices',
        recurringView: 'recurring-invoices/view',
        agingAnalysis: 'analytics',
        reminders: 'reminders',
        quotations: 'quotations',
        quotationCreate: 'create-quotation',
        quotationEdit: 'edit-quotation/:id',
        quotationDetails: 'quotation-details/:id',
    },
    giftcards: {
        index: 'gift-cards',
        details: 'details',
        id: '/:id',
        orderHistory: 'order-history',
        success: 'success',
        failure: 'failure',
    },
    settings: {
        index: 'settings',
    },
    payroll: {
        index: 'payroll',
        payrollAccountSetup: 'set-up-payroll-account',
        payrollAccountProgress: 'payroll-account-progress',
        payrollBankAccountProgress: 'payroll-bank-account-progress',
        salaryDashboard: 'salary-dashboard',
        salaryEmployees: 'salary-employees',
        salaryPastEmployees: 'salary-past-employees',
        salaryProcess: 'process-salary',
        salaryHistory: 'salary-history',
        salaryHistoryDetails: 'salary-history-details',
        payrollHistoryView: 'payroll-history-view',
        salaryStats: 'salary-stats',
        manageBanks: 'manage-banks',
        manageBankTransactions: 'all-transactions',
        announcements: 'announcements',
        id: '/:id',
        eId: '/:eId',
        salaryProfile: 'salary-profile',
        addEmployee: 'add-employee',
        addNewHire: 'add-new-hire',
        newHireProfile: 'new-hire-profile',
        employeesSalary: 'employees-salary',
        employeeProfile: 'employee-profile',
        employees: 'employees',
        payrollSettings: 'HR-settings',
        leaveConfig: 'leave-configuration',
        complianceSettings: 'compliance-settings',
        activityCalendar: 'activity-calendar',
        bulkUpload: 'bulk-upload',
        employeeLeave: 'employee-Leaves',
        timesheet: 'timesheet',
        wpsRegistration: 'wps-registration',
        employeeSuccess: 'success',
        employeeAdded: 'employee-added',
        employeeReimbursement: 'employee-reimbursements',
        reports: 'reports',
        allDocuments: 'all-documents',
        documentsDetails: 'documents-details',
        leaveSummary: 'leave-summary/:id',
        employeeSalaryProfile: 'employee-salary-profile',
        payrollRecordSuccess: 'payroll-record-success',
        ctcCalculator: 'ctc-calculator',
    },
    pekoCloud: {
        index: 'hub',
        settings: 'settings',
        taskToDo: 'task-to-do',
        companyDocuments: 'company-documents',
        ownershipDocuments: 'ownership-documents',
        financials: 'financials',
        employeeDetails: 'employee-details',
        subscriptions: 'subscriptions',
        assets: 'assets',
        assetsDetails: 'assets-details',
        fleet: 'fleet',
        fleetDetails: 'fleet-details',
        chequeBookDetails: 'cheque-book-details',
        chequeDetails: 'cheque-details',
    },
    pekoCredits: {
        index: 'peko-credit',
    },
    turbo: {
        index: 'turbo',
        addVehicle: 'add-vehicle',
        viewDetails: 'view-vehicle-details',
        driverProfiles: 'driver-profiles',
        addDriver: 'add-driver',
        driverDetails: 'view-driver-details',
        documentCentre: 'document-center',
        manageSubscription: 'manage-subscription',
        manageFleet: 'manage-fleet',
        operationLog: 'operations-log',
        challans: 'challans',
        challanOrders: 'orders',
        vehicleReports: 'vehicle-reports',
        selectVehicle: 'select-vehicle',
        valuationReport: 'valuation',
        historyReport: 'history',
        inspection: 'inspection',
        inspectionBooking: 'book',
        reportOrders: 'orders',
        reportOrderDetails: 'order-details',
        // Car Reports' own post-payment screen, reached via the payment slice's
        // `successPath` instead of the shared /payments/payment-success page.
        reportSuccess: 'success',
    },
    plans: {
        index: 'plans',
        reviewOrder: 'review-order',
        paymentsuccess: 'payment-success',
        paymentPending: 'payment-pending',
        paymentFailure: 'payment-failure',
    },
    pekoWallet: {
        index: 'peko-wallet',
        paymentsuccess: 'topup-success',
        transactionHistory: 'wallet-history',
        paymentFailure: 'payment-failure',
    },
    profile: {
        index: 'profile',
        kyb: 'One-KYB',
    },
    verificationSuite: {
        index: 'verification-suite',
        verificationHistory: 'verification-history',
        verificationDetails: 'verification-details',
        settings: 'settings',
        reviewOrder: 'review-order',
    },
    domainHosting: {
        index: 'domain-&-hosting',
        cart: 'cart',
        checkout: 'checkout',
        vpsServer: 'vps-server',
        vpsServerDetail: 'vps-server/detail',
        sharedHosting: 'shared-hosting',
        sharedHostingDetail: 'shared-hosting/detail',
        googleWorkspace: 'google-workspace',
        googleWorkspaceDetail: 'google-workspace/detail',
        googleWorkspaceOrder: 'google-workspace/order-processing',
        titanEmail: 'titan-email',
        titanEmailDetail: 'titan-email/detail',
        titanEmailOrder: 'titan-email/order-processing',
        domainAssign: 'domain-assign',
        manageSubscription: 'manage-subscription',
    },
    governmentServices: {
        index: 'government-services',
        explore: 'explore',
        service: 'service',
        application: 'application',
    },
    // Not mounted (feature hidden); kept for the dormant CompanyIncorporation domain
    companyIncorporation: {
        index: '/more-services/company-incorporation',
        form: 'apply',
        payment: 'payment',
        tracking: 'tracking',
    },
    businessRegistration: {
        index: '/more-services/business-registration',
        form: 'apply',
        register: 'register',
        payment: 'payment',
        tracking: 'tracking',
        applications: 'applications',
    },
    globalBusinessSetup: {
        index: 'global-business-setup',
        locations: 'locations',
        owners: 'owners',
        companyDetails: 'company-details',
        applications: 'applications',
        pendingApplications: 'pending-applications',
        viewRequest: 'view-details',
        firstStep: 'choose-jurisdiction',
        getStarted: 'get-started',
        new: 'new-application',
        edit: 'edit-application',
        review: 'review-application',
        companyRegisterd: 'registered',
        documents: 'company-information',
        paymentsuccess: 'payment-success',
        reviewCompany: 'review-company-information',
        paymentsummary: 'payment-summary',
        getQuote: 'get-quote',
        details: 'details',
        ongoingSetups: 'ongoing-setups',
        renewals: 'renewals',
    },
    procure: {
        index: 'procure',
        dashboard: 'dashboard',
        purchaseRequests: {
            index: 'purchase-requests',
            create: 'create',
            view: ':id',
            edit: ':id/edit',
        },
        rfq: {
            index: 'rfq',
            create: 'create',
            view: ':id',
            edit: ':id/edit',
        },
        proposals: {
            index: 'proposals',
            view: ':proposalId',
            compare: 'compare/:rfqId',
        },
        purchaseOrders: {
            index: 'purchase-orders',
            view: ':poId',
            create: 'create',
            edit: ':poId/edit',
            uploadInvoice: ':poId/upload-invoice',
        },
        invoicing: {
            index: 'invoices',
            view: ':invoiceId',
        },
        vendor: {
            index: 'vendor',
            create: 'create',
            view: ':id',
            edit: 'edit/:id',
        },
        onboarding: 'payment-onboarding',
        activity: 'activity',
    },
    ecommerce: {
        index: 'peko-commerce',
        plan: 'plan-details',
        reviewOrder: 'subscription',
        paymentsuccess: 'payment-success',
    },

    // ----ADMIN ROUTES----
    manage: {
        index: `${ROOTS.ADMIN}/manage`,
        bulk: 'bulk',
        softwareProducts: 'software-products',
        softwarePlans: 'software-plans',
        officeAddress: 'office-address',
        workspaces: 'workspaces',
        corporateTaxRegistration: 'corporate-tax-registration',
        pekoWorks: 'peko-works',
        workPlans: 'work-plans',
        giftCards: 'gift-cards',
        legalTemplates: 'legal-templates',
        connect: 'connect',
        eDocs: 'business-docs',
        govtServices: 'government-services',
        attestationCategory: 'attestation',
        vendorPayouts: 'vendor-payout',
        bussinessEmails: 'business-emails',
        bussinessEmailsplans: 'business-emails-plans',
        domainHostingPlans: 'domain-&-hosting-plans',
        domainHostingCancellations: 'domain-&-hosting-cancellations',
        carReportPlans: 'car-report-plans',
        hike: 'hike',
        esimPlans: 'esim-plans',
        invoiceKyb: 'invoice-kyb',
        collectorKyb: 'collector-kyb',
        walletDenomination: 'peko-wallet',
        domainTlds: 'domain-tlds',
        // office-supplies
        returnRequest: 'return-request',
        cancelAndRefunds: 'cancel-&-refunds',
        orders: 'orders',
        // nested under `orders/` so RoleGuard's [3]='orders' service check passes
        orderDetails: 'orders/details/:id',
        issueDetails: 'orders/issues/:id',
        issues: 'issues',
        products: 'products',
        // nested under `products/` so RoleGuard's [3]='products' service check passes
        productDetails: 'products/details/:id',
        bulkUpload: 'bulk-upload',
        // announcements
        notifications: 'notifications',
        // payment links
        paymentLinks: 'payment-links',
        kybVerifications: 'kyb-verifications',
        paymentMethods: 'payment-methods',
        // Payroll
        companyDocuments: 'company-documents',
        // Bill Payments
        billPayments: 'bill-payments',
        // Airline
        airlineAirports: 'airline-airports',
        // Business Registration
        businessRegistrationAdmin: 'business-registration',
        // Compliance
        compliance: 'compliance',
        // Payout Onboarding
        payoutOnboarding: 'payout-onboarding',
        // Corporate Cards (card path = getPathFromLabel('Applications'))
        corporateCardApplications: 'applications',
        corporateCardApplicationDocuments: 'applications/:corporateId/documents',
        corporateCardTerminations: 'termination-requests',
        corporateCardClosures: 'account-closure-requests',
        corporateCardDocumentLimits: 'document-size-limits',
        // Logistics
        logisticsCorporate: 'logistics-corporate',
    },
    users: {
        index: `${ROOTS.ADMIN}/users`,
        corporateUser: 'corporate-users',
        corporateLookup: 'corporate-lookup',
        corporateCardLookup: 'corporate-card-lookup',
        systemUser: 'system-users',
        roles: 'roles',
        // settings -> users
        systemUserConfiguration: 'system-user-configuration',
        corporateUserConfiguration: 'corporate-user-configuration',
        PartnerRoles: 'Partner-Permissions',
        Partners: 'partners',
        partnerServices: 'partner-services',
    },
    accounts: {
        index: `${ROOTS.ADMIN}/accounts`,
        selfTransfer: 'self-transfer',
        transferFunds: 'transfer-funds',
        createTransactions: 'create-transaction',
        bulkRefund: 'bulk-refund',
        refundTransactions: 'refund-transactions',
    },
    settingsAdmin: {
        index: `${ROOTS.ADMIN}/settings`,
        vendor: 'vendors',
        serviceOperators: 'service-operators',
        PackagePage: 'packages',
        Cashback: 'cashback',
        SubscriptionCodes: 'subscription-codes',
        DisabledService: 'disable-services',
        Banners: 'banners',
        Categories: 'categories',
        RefferalCode: 'referral-code',
        Templates: 'invoice-templates',
        AccessCode: 'access-code',
        CouponCode: 'coupon-code',
        WhatsAppNumbers: 'peko-whatsapp-numbers',
        Branding: 'branding',
        IPWhitelist: 'ip-whitelist',
        subscriptionReminders: 'subscription-reminders',
        servicePackages: 'service-packages',
        serviceRule: 'service-rule',
        pekoCredits: 'peko-credits',
        businessRegistrationCatalog: 'business-registration-catalog',
    },
    needHelpAdmin: {
        tickets: 'tickets',
    },
    systemConfiguration: {
        passwordPolicy: 'password-policy',
        passwordProtection: 'password-protection',
        applicationPolicy: 'application-policy',
    },
    reportsAdmin: {
        SubscriptionsTable: 'subscriptions',
        Vendors: 'vendors',
        Corporate: 'corporate',
        Orders: 'orders',
        SoftwareOrders: 'software-orders',
        Esim: 'esim',
        OrderContent: 'peko-works',
        ConnectionRequests: 'connection-requests',
        Workspace: 'workspace-orders',
        Invoices: 'invoices',
        Attestation: 'attestations',
        Transactions: 'transactions',
        Esign: 'eSign',
        Airline: 'airline-cancellation',
        HotelCancellation: 'hotel-cancellation',
        HotelBookings: 'hotel-bookings',
        AirlineBookings: 'airline-bookings',
        AirlineModification: {
            index: 'airline-modification',
            modificationRequest: 'request',
        },
        ReportScheduling: 'scheduling-reports',
        PaymentLinks: 'payment-links',
        BusinessEmails: 'business-emails',
        TransactionsReport: 'transaction-report',
        VerificationReports: 'verification-reports',
        GovtServicesApplications: 'govt-services-applications',
        InsuranceQuoteRequests: 'insurance-quote-requests',
        // accounts -> reports
        walletReport: 'wallet-reports',
        // users -> reports
        pendingSignups: 'pending-sign-ups',
        // domain & hosting
        DomainHostingRefunds: 'domain-&-hosting-refunds',
        SubscriptionWebhooks: 'subscription-renewals',
        globalBusinessSetupApplications: 'global-business-setup-applications',
        globalBusinessSetupRenewals: 'global-business-setup-renewals',
    },
    admin: {
        index: `${ROOTS.ADMIN}`,
        dashboard: `${ROOTS.ADMIN}/dashboard`,
        users: `${ROOTS.ADMIN}/users`,
        accounts: `${ROOTS.ADMIN}/accounts`,
        reports: `${ROOTS.ADMIN}/reports`,
        officeSupplies: `${ROOTS.ADMIN}/office-supplies`,
        support: `${ROOTS.ADMIN}/support`,
        manage: `${ROOTS.ADMIN}/manage`,
        bulkUpload: `${ROOTS.ADMIN}/bulk-upload`,
        settings: `${ROOTS.ADMIN}/settings`,
        needHelp: `${ROOTS.ADMIN}/need-help`,
        announcement: `${ROOTS.ADMIN}/announcement`,
    } as Record<string, string>,
    ecomManager: {
        index: `${ROOTS.ECOM}`,
        dashboard: `${ROOTS.ECOM}/dashboard`,
        orders: `${ROOTS.ECOM}orders`,
        needHelp: `${ROOTS.ECOM}/need-help`,
        officeSupplies: `${ROOTS.ECOM}/officeSupplies`,
        returnAndRefunds: `${ROOTS.ECOM}/returnAndRefunds`,
        cancelAndRefunds: `${ROOTS.ECOM}/cancelAndRefunds`,
        vendors: `${ROOTS.ECOM}/vendors`,
        categories: `${ROOTS.ECOM}/categories`,
        products: `${ROOTS.ECOM}/products`,
    } as Record<string, string>,
    systemUser: {
        profile: `${ROOTS.SYSYTEM_USER}/profile`,
        index: `${ROOTS.SYSYTEM_USER}`,
        dashboard: `${ROOTS.SYSYTEM_USER}/dashboard`,
        users: `${ROOTS.SYSYTEM_USER}/users`,
        payrollConfig: `${ROOTS.SYSYTEM_USER}/payroll`,
        accounts: `${ROOTS.SYSYTEM_USER}/accounts`,
        reports: `${ROOTS.SYSYTEM_USER}/reports`,
        officeSupplies: `${ROOTS.SYSYTEM_USER}/office-supplies`,
        support: `${ROOTS.SYSYTEM_USER}/support`,
        manage: `${ROOTS.SYSYTEM_USER}/manage`,
        systemConfiguration: `${ROOTS.SYSYTEM_USER}/system-configuration`,
        bulkUpload: `${ROOTS.SYSYTEM_USER}/bulk-upload`,
        settings: `${ROOTS.SYSYTEM_USER}/settings`,
        needHelp: `${ROOTS.SYSYTEM_USER}/need-help`,
        announcement: `${ROOTS.SYSYTEM_USER}/announcements`,
    } as Record<string, string>,
    employee: {
        index: `${ROOTS.EMPLOYEE}`,
        home: `${ROOTS.EMPLOYEE}`,
        onboarding: `${ROOTS.EMPLOYEE}/onboarding`,
        profile: `${ROOTS.EMPLOYEE}/profile`,
        attendance: `${ROOTS.EMPLOYEE}/attendance`,
        payslips: `${ROOTS.EMPLOYEE}/payslips`,
        leaves: `${ROOTS.EMPLOYEE}/leaves`,
        reimbursements: `${ROOTS.EMPLOYEE}/reimbursements`,
        documents: `${ROOTS.EMPLOYEE}/documents`,
    } as Record<string, string>,
    // PROTOTYPE-SETUP: ESS prototype tabs, mounted inside the corporate dashboard layout (not /employee) so
    // the sidebar stays visible. Same keys as `employee` so the reused ESS pages can swap bases.
    essEmployee: {
        index: '/ess-employee',
        home: '/ess-employee',
        profile: '/ess-employee/profile',
        attendance: '/ess-employee/attendance',
        payslips: '/ess-employee/payslips',
        leaves: '/ess-employee/leaves',
        reimbursements: '/ess-employee/reimbursements',
        documents: '/ess-employee/documents',
    } as Record<string, string>,
    essManager: {
        index: '/ess-manager',
    },
};
