export const soundboxData = [
    {
        image: 'Paytm-card',
        descImage: 'Paytm-card-type',
        description: 'Now accept card payments on your Paytm Soundbox ',
    },
    {
        image: 'Paytm-card',
        descImage: 'Paytm-card-type',
        description: 'Now accept card payments on your Paytm Soundbox ',
    },
    {
        image: 'Paytm-card',
        descImage: 'Paytm-card-type',
        description: 'Now accept card payments on your Paytm Soundbox ',
    },
    {
        image: 'Paytm-card',
        descImage: 'Paytm-card-type',
        description: 'Now accept card payments on your Paytm Soundbox ',
    },
    {
        image: 'Paytm-card',
        descImage: 'Paytm-card-type',
        description: 'Now accept card payments on your Paytm Soundbox ',
    },
    {
        image: 'Paytm-card',
        descImage: 'Paytm-card-type',
        description: 'Now accept card payments on your Paytm Soundbox ',
    },
    {
        image: 'Paytm-card',
        descImage: 'Paytm-card-type',
        description: 'Now accept card payments on your Paytm Soundbox ',
    },
];
export const tableData = [
    {
        key: '1',
        model: 'Card Soundbox',
        battery: '5 Days',
        speaker: '4 W',
        avatar: 'cardSoundBoxDetails',
        connectivity: '4G',
        charging: 'TYPE C',
        display: 'Yes',
        bluetooth: 'No',
    },
    {
        key: '1',
        model: 'Card Soundbox',
        battery: '5 Days',
        speaker: '4 W',
        avatar: 'pocketSoundBoxDetails',
        connectivity: '4G',
        charging: 'TYPE C',
        display: 'Yes',
        bluetooth: 'No',
    },
    {
        key: '1',
        model: 'Card Soundbox',
        battery: '5 Days',
        speaker: '4 W',
        avatar: 'musicSoundBoxDetails',
        connectivity: '4G',
        charging: 'TYPE C',
        display: 'Yes',
        bluetooth: 'No',
    },
    {
        key: '1',
        model: 'Card Soundbox',
        battery: '5 Days',
        speaker: '4 W',
        avatar: 'soundboxFiveDetails',
        connectivity: '4G',
        charging: 'TYPE C',
        display: 'Yes',
        bluetooth: 'No',
    },
    {
        key: '1',
        model: 'Card Soundbox',
        battery: '5 Days',
        speaker: '4 W',
        avatar: 'soundboxThreeDetails',
        connectivity: '4G',
        charging: 'TYPE C',
        display: 'Yes',
        bluetooth: 'No',
    },
    {
        key: '1',
        model: 'Card Soundbox',
        battery: '5 Days',
        speaker: '4 W',
        avatar: 'soundBoxTwoDetails',
        connectivity: '4G',
        charging: 'TYPE C',
        display: 'Yes',
        bluetooth: 'No',
    },
    {
        key: '1',
        model: 'Card Soundbox',
        battery: '5 Days',
        speaker: '4 W',
        avatar: 'soundBoxDetails',
        connectivity: '4G',
        charging: 'TYPE C',
        display: 'Yes',
        bluetooth: 'No',
    },
];
