import {
    CheckCircleFilled,
    CheckOutlined,
    InfoCircleOutlined,
    SyncOutlined,
    WarningOutlined,
} from '@ant-design/icons';
import { Button, Flex, Typography } from 'antd';

import type { FetchState } from '../../utils/gstr2bTypes';

interface Props {
    fetchState: FetchState;
    periodLabel: string;
    itcAvailable?: number;
    itcNotAvailable?: number;
    generatedDate?: string;
    onRegenerate: () => void;
    onFetchStateChange: (state: FetchState) => void;
}

const FetchStateBanner = ({
    fetchState,
    periodLabel,
    itcAvailable,
    itcNotAvailable,
    generatedDate,
    onRegenerate,
    onFetchStateChange,
}: Props) => {
    if (fetchState === 'idle') {
        return (
            <Flex
                gap={10}
                align="flex-start"
                className="border border-[#cbd5e1] rounded-[14px] px-6 py-5"
                style={{ backgroundColor: '#f8fafc' }}
            >
                <InfoCircleOutlined
                    style={{ fontSize: 18, color: '#475569', flexShrink: 0, marginTop: 2 }}
                />
                <Flex vertical gap={4}>
                    <Typography.Text
                        className="font-medium"
                        style={{ fontSize: 16, color: '#1e293b' }}
                    >
                        GSTR-2B not fetched yet for {periodLabel}
                    </Typography.Text>
                    <Typography.Text className="text-xs" style={{ color: '#475569' }}>
                        GSTR-2B is auto-generated by the GST portal on the 14th of each month. Click
                        Fetch GSTR-2B to pull the latest data.
                    </Typography.Text>
                </Flex>
            </Flex>
        );
    }

    if (fetchState === 'fetching') {
        return (
            <Flex
                gap={10}
                align="flex-start"
                className="border border-[#cbd5e1] rounded-[14px] px-6 py-5"
                style={{ backgroundColor: '#fff' }}
            >
                <SyncOutlined
                    spin
                    style={{ fontSize: 18, color: '#475569', flexShrink: 0, marginTop: 2 }}
                />
                <Flex vertical gap={4}>
                    <Typography.Text
                        className="font-medium"
                        style={{ fontSize: 16, color: '#1e293b' }}
                    >
                        Fetching GSTR-2B from GST Portal...
                    </Typography.Text>
                    <Typography.Text className="text-xs" style={{ color: '#475569' }}>
                        Querying portal for {periodLabel} purchase data
                    </Typography.Text>
                </Flex>
            </Flex>
        );
    }

    if (fetchState === 'loaded') {
        return (
            <Flex
                gap={10}
                align="flex-start"
                className="border border-[#81cf92] rounded-[14px] px-6 py-4"
                style={{ backgroundColor: '#ecfdf5' }}
            >
                <CheckCircleFilled
                    style={{ fontSize: 18, color: '#43b75d', flexShrink: 0, marginTop: 2 }}
                />
                <Flex vertical gap={4}>
                    <Typography.Text
                        className="font-medium"
                        style={{ fontSize: 16, color: '#1e293b' }}
                    >
                        GSTR-2B loaded · {periodLabel}
                    </Typography.Text>
                    <Flex gap={16}>
                        {itcAvailable !== undefined && (
                            <Typography.Text className="text-xs" style={{ color: '#43b75d' }}>
                                ITC Available:{' '}
                                <strong>₹{itcAvailable.toLocaleString('en-IN')}</strong>
                            </Typography.Text>
                        )}
                        {itcNotAvailable !== undefined && (
                            <Typography.Text className="text-xs" style={{ color: '#ef4444' }}>
                                ITC Not Available:{' '}
                                <strong>₹{itcNotAvailable.toLocaleString('en-IN')}</strong>
                            </Typography.Text>
                        )}
                        {generatedDate && (
                            <Typography.Text className="text-xs" style={{ color: '#475569' }}>
                                Generated: {generatedDate}
                            </Typography.Text>
                        )}
                    </Flex>
                </Flex>
            </Flex>
        );
    }

    if (fetchState === 'regen-polling') {
        return (
            <Flex
                gap={10}
                align="flex-start"
                className="border border-[#cbd5e1] rounded-[14px] px-6 py-5"
                style={{ backgroundColor: '#f8fafc' }}
            >
                <SyncOutlined
                    spin
                    style={{ fontSize: 18, color: '#475569', flexShrink: 0, marginTop: 2 }}
                />
                <Flex vertical gap={4}>
                    <Typography.Text
                        className="font-medium"
                        style={{ fontSize: 16, color: '#1e293b' }}
                    >
                        Regenerating GSTR-2B...
                    </Typography.Text>
                    <Typography.Text className="text-xs" style={{ color: '#475569' }}>
                        Checking status every 3 seconds. This may take a moment.
                    </Typography.Text>
                </Flex>
            </Flex>
        );
    }

    return (
        <Flex
            align="flex-start"
            justify="space-between"
            wrap="wrap"
            gap={12}
            className="border border-[#fcd34d] rounded-[14px] px-4 sm:px-6 py-4"
            style={{ backgroundColor: '#fffbeb' }}
        >
            <Flex gap={10} align="flex-start" style={{ flex: '1 1 200px', minWidth: 0 }}>
                <WarningOutlined
                    style={{ fontSize: 18, color: '#f59e0b', flexShrink: 0, marginTop: 2 }}
                />
                <Flex vertical gap={4}>
                    <Typography.Text
                        className="font-medium"
                        style={{ fontSize: 16, color: '#f59e0b' }}
                    >
                        Regenerate GSTR-2B?
                    </Typography.Text>
                    <Typography.Text className="text-xs" style={{ color: '#92400e' }}>
                        This triggers a fresh GSTR-2B computation on the GST portal based on your
                        current IMS actions (accepted/rejected invoices). Use this only if
                        you&apos;ve updated your IMS and want the 2B to reflect those changes.
                    </Typography.Text>
                    <Typography.Text className="text-xs font-medium" style={{ color: '#92400e' }}>
                        Note: Regeneration is not allowed after GSTR-3B is filed for this period.
                    </Typography.Text>
                </Flex>
            </Flex>
            <Flex gap={8} wrap="wrap">
                <Button
                    icon={<CheckOutlined />}
                    style={{ borderColor: '#ff4f4f', color: '#ff4f4f' }}
                    onClick={onRegenerate}
                >
                    Yes, Regenerate
                </Button>
                <Button onClick={() => onFetchStateChange('loaded')}>Cancel</Button>
            </Flex>
        </Flex>
    );
};

export default FetchStateBanner;
