import { InfoCircleOutlined } from '@ant-design/icons';
import { Checkbox, Input, Select, Typography } from 'antd';

import { MoaAoaController } from './useMoaAoa';

type AutoGeneratedPanelProps = {
    controller: MoaAoaController;
    onPreview: () => void;
};

export default function AutoGeneratedPanel({ controller, onPreview }: AutoGeneratedPanelProps) {
    const {
        objectTemplate,
        selectTemplate,
        templateOptions,
        mainObjectClause,
        setMainObjectClause,
    } = controller;
    const { ancillary, ancillaryItems, toggleAncillary } = controller;

    return (
        <div className="space-y-4">
            <div className="flex items-center gap-2" style={{ color: '#FF4F4F' }}>
                <p className="text-sm font-medium">✦ Auto-Generated MOA Content</p>
            </div>

            <div>
                <p className="text-sm font-semibold text-gray-800">
                    Memorandum &amp; Articles of Association
                </p>
                <p className="text-xs text-gray-500">
                    Define the foundational documents for your company - MOA outlines objectives,
                    AOA defines internal rules
                </p>
            </div>

            <div>
                <p className="block text-sm font-medium text-gray-700 mb-1">
                    Select main object template
                </p>
                <Select
                    className="w-full"
                    value={objectTemplate}
                    options={templateOptions.map(t => ({ label: t.label, value: t.key }))}
                    onChange={key => selectTemplate(key)}
                />
            </div>

            <div>
                <p className="block text-sm font-medium text-gray-700 mb-1">Main Object Clause</p>
                <Input.TextArea
                    rows={4}
                    value={mainObjectClause}
                    onChange={e => setMainObjectClause(e.target.value)}
                />
                <Typography.Text type="secondary" className="mt-1 block text-xs">
                    This clause goes into Clause III(a) of your MOA. Changing the template above
                    will update this text. Use tokens like <code>{'{{company_name}}'}</code> or any
                    field name to inject form data.
                </Typography.Text>
            </div>

            <div>
                <p className="mb-2 text-sm font-medium text-gray-700">
                    Ancillary / Incidental Objects
                </p>
                <div className="rounded-xl border border-gray-200 p-4">
                    <div className="flex flex-col gap-3">
                        {ancillaryItems.map(object => (
                            <div key={object.key} className="flex items-start">
                                <Checkbox
                                    checked={ancillary.includes(object.key)}
                                    onChange={() => toggleAncillary(object.key)}
                                />
                                <span className="text-sm text-gray-700 ml-2">{object.label}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <div className="flex items-start gap-2 rounded-lg bg-gray-100/70 p-3">
                <InfoCircleOutlined className="mt-0.5 shrink-0 text-gray-400 text-base" />
                <p className="text-xs text-gray-500">
                    The pre-selected ancillary objects cover the most common incidental activities
                    for most businesses. You can select or deselect as needed.
                </p>
            </div>

            <button
                type="button"
                className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition"
                onClick={onPreview}
            >
                Preview Your Auto-Generated MOA
            </button>
        </div>
    );
}
