import { Button } from 'antd';

import AutoGeneratedPanel from './AutoGeneratedPanel';
import { MoaAoaController } from './useMoaAoa';
import RadioCard from '../../ui/RadioCard';
import UploadBox from '../../ui/UploadBox';

type MoaSectionProps = {
    controller: MoaAoaController;
    onPreview: () => void;
};

export default function MoaSection({ controller, onPreview }: MoaSectionProps) {
    return (
        <section className="space-y-3">
            <div>
                <h3 className="text-base font-semibold text-gray-800">
                    Memorandum of Association (MOA)
                </h3>
                <p className="text-sm text-gray-500">
                    The MOA defines the company&apos;s objectives, powers, and scope of operations.
                    It&apos;s a public document.
                </p>
            </div>

            <RadioCard
                action={
                    <Button size="small" onClick={onPreview}>
                        Preview
                    </Button>
                }
                badge="(Auto generated)"
                selected={controller.moaType === 'standard'}
                title="Standard MOA Template"
                onSelect={() => controller.setMoaType('standard')}
            >
                <AutoGeneratedPanel controller={controller} onPreview={onPreview} />
            </RadioCard>

            <RadioCard
                badge="(Upload your own)"
                selected={controller.moaType === 'custom'}
                title="Custom MOA"
                onSelect={() => controller.setMoaType('custom')}
            >
                <UploadBox
                    error={controller.customMoaFileError}
                    value={controller.customMoaFile}
                    onChange={controller.setCustomMoaFile}
                />
            </RadioCard>
        </section>
    );
}
