export const epfoIndustryOptions: string[] = [
    'Cement',
    'Cigarettes',
    'Electrical, Mechanical or General Engineering Products',
    'Iron and Steel',
    'Paper (incl. pulp, paperboard, straw-board)',
    'Textiles (Cotton / Wool / Jute / Silk — natural or artificial)',
    'Jute',
    'Edible Oils and Fats',
    'Sugar',
    'Rubber and Rubber Products',
    'Electricity — Generation, Transmission and Distribution',
    'Tea (except Assam, where a separate PF Scheme exists)',
    'Printing — other than newspaper establishments (incl. bookbinding)',
    'Mineral Oil Refining',
    'Glass',
    'Stoneware Pipes',
    'Crockery',
    'Matches',
    'Shellac',
    'Chemical and Pharmaceutical Preparations',
    'Soap',
    'Dyes and Dyestuffs',
    'Inks',
    'Fertilisers',
    'Explosives',
    'Asbestos Products',
    'Cement Products',
    'Electrical Porcelain Insulators',
    'Starch Industry',
    'Leather and Leather Products',
    'Fruit and Vegetable Preservation Industry',
    'Petroleum or Natural Gas — Exploration, Prospecting, Drilling or Production',
    'Cashewnut Industry',
    'Confectionery Industry',
    'Aerated Water Industry (soft drinks, carbonated water)',
    'Distilling & Rectifying of Spirits and Blending',
    'Paint and Varnish Industry',
    'Bone Crushing Industry',
    'Pickers Industry',
    'Milk and Milk Products Industry',
    'Non-Ferrous Metals and Alloys (in form of ingots)',
    'Bread Industry',
    'Stemming or Re-drying of Tobacco Leaf Industry',
    'Agarbatti (incl. Dhoop and Dhoopbatti) Industry',
    'Coir Industry (excluding spinning sector)',
    'Tobacco Industry (cigars, zarda, snuff, quivam, guraku)',
    'Paper Products Industry',
    'Licensed Salt Industry',
    'Myrobalan Extract / Vegetable Tanning Industry',
    'Brick Industry',
    'All Industries based on Asbestos as Principal Raw Material',
    'Industries Manufacturing Iron Ore Pellets',
    'Linoleum Industry',
    'Jute Bailing Industry',
    'Rice / Flour / Dal Milling',
    'Automobile Repairing and Servicing',
    'Tobacco Products — Bidis',
    'Industrial and Power Alcohol Industry',
    'Wood and Wood Products Industry',
    'Rubber Plantations',
    'Coffee Plantations',
    'Cardamom Plantations',
    'Tea Plantations (Assam — separate scheme applicable)',
    'Vegetable Oil Industry (other than edible oil)',
    'Stone Quarries for Chips (Builders etc.)',
    'Flour Mills',
    'Hosiery Industry',
    'Iron Ore Mines',
    'Limestone / Dolomite Mines',
    'Mica Mines',
    'Manganese Ore Mines',
    'Chromite Mines',
    'Kyanite Mines',
    'Sillimanite Mines',
    'Fire Clay Mines',
    'Bauxite Mines',
    'Copper Mines',
    'Lead and Zinc Mines',
    'Gold Mines',
    'Magnesite Mines',
    'Tin Mines',
    'Apatite Mines',
    'Rock Phosphate Mines',
    'Gypsum Mines',
    'China Clay / Kaolin Mines',
    'Feldspar Mines',
    'Graphite Mines',
    'Corundum Mines',
    'Salt Mines / Salt Works',
    'Garnet Industry',
    'Fire Bricks Industry',
    'Electrical Porcelain Industry',
    'Ceramics Industry',
    'Engineering Contractors',
    'Architects',
    'Agriculture Farms',
    'Construction Industry / Civil Construction',
    'Trading and Commercial Establishments',
    'Establishments of Exporters, Importers, Advertisers, Commission Agents and Brokers',
    'Commodity and Stock Exchanges',
    'Road Motor Transport Industry',
    'Catering Industry — Hotels and Restaurants',
    'Cinema Industry including Cinema Theatres',
    'Newspaper Establishments',
    'Insurance Companies',
    'Non-Banking Financial Companies (NBFCs)',
    'Warehousing (other than Govt. warehouses)',
    'Educational Institutions — Schools, Colleges, Technical Institutes',
    'Hospitals and Nursing Homes',
    'Clubs, Gymkhanas and Associations',
    'Courier Services',
    'Security Services / Manpower Supply Agencies',
    'Information Technology (IT) Companies',
    'IT-Enabled Services — ITES / BPO',
    'Banks (as notified)',
    'Co-operative Societies (with aid of power, 20+ employees)',
    'Societies and Trusts (employing 20+ persons)',
];
