// Country list shared by the IndiaFilings vendor (countries.json, 24-07) so the
// values we send match their DB exactly. value = vendor canonical country_name
// (uppercase); label = display nicename. India is pinned to the top.
export const COUNTRIES: { label: string; value: string }[] = [
    { label: "India", value: "INDIA" },
    { label: "Afghanistan", value: "AFGHANISTAN" },
    { label: "Aland Islands", value: "ALAND ISLANDS" },
    { label: "Albania", value: "ALBANIA" },
    { label: "Algeria", value: "ALGERIA" },
    { label: "American Samoa", value: "AMERICAN SAMOA" },
    { label: "Andorra", value: "ANDORRA" },
    { label: "Angola", value: "ANGOLA" },
    { label: "Anguilla", value: "ANGUILLA" },
    { label: "Antigua and Barbuda", value: "ANTIGUA AND BARBUDA" },
    { label: "Argentina", value: "ARGENTINA" },
    { label: "Armenia", value: "ARMENIA" },
    { label: "Aruba", value: "ARUBA" },
    { label: "Asia / Pacific Region", value: "ASIA PACIFIC REGION" },
    { label: "Australia", value: "AUSTRALIA" },
    { label: "Austria", value: "AUSTRIA" },
    { label: "Azerbaijan", value: "AZERBAIJAN" },
    { label: "Bahamas", value: "BAHAMAS" },
    { label: "Bahrain", value: "BAHRAIN" },
    { label: "Bangladesh", value: "BANGLADESH" },
    { label: "Barbados", value: "BARBADOS" },
    { label: "Belarus", value: "BELARUS" },
    { label: "Belgium", value: "BELGIUM" },
    { label: "Belize", value: "BELIZE" },
    { label: "Benin", value: "BENIN" },
    { label: "Bermuda", value: "BERMUDA" },
    { label: "Bhutan", value: "BHUTAN" },
    { label: "Bolivia", value: "BOLIVIA" },
    { label: "Bonaire, Sint Eustatius and Saba", value: "BONAIRE, SINT EUSTATIUS AND SABA" },
    { label: "Bosnia and Herzegovina", value: "BOSNIA AND HERZEGOVINA" },
    { label: "Botswana", value: "BOTSWANA" },
    { label: "Bouvet Island", value: "BOUVET ISLAND" },
    { label: "Brazil", value: "BRAZIL" },
    { label: "British Indian Ocean Territory", value: "BRITISH INDIAN OCEAN TERRITORY" },
    { label: "Brunei Darussalam", value: "BRUNEI DARUSSALAM" },
    { label: "Bulgaria", value: "BULGARIA" },
    { label: "Burkina Faso", value: "BURKINA FASO" },
    { label: "Burundi", value: "BURUNDI" },
    { label: "Cambodia", value: "CAMBODIA" },
    { label: "Cameroon", value: "CAMEROON" },
    { label: "Canada", value: "CANADA" },
    { label: "Cape Verde", value: "CAPE VERDE" },
    { label: "Cayman Islands", value: "CAYMAN ISLANDS" },
    { label: "Central African Republic", value: "CENTRAL AFRICAN REPUBLIC" },
    { label: "Chad", value: "CHAD" },
    { label: "Chile", value: "CHILE" },
    { label: "China", value: "CHINA" },
    { label: "Christmas Island", value: "CHRISTMAS ISLAND" },
    { label: "Cocos (Keeling) Islands", value: "COCOS (KEELING) ISLANDS" },
    { label: "Colombia", value: "COLOMBIA" },
    { label: "Comoros", value: "COMOROS" },
    { label: "Congo", value: "CONGO" },
    { label: "Congo, the Democratic Republic of the", value: "CONGO, THE DEMOCRATIC REPUBLIC OF THE" },
    { label: "Cook Islands", value: "COOK ISLANDS" },
    { label: "Costa Rica", value: "COSTA RICA" },
    { label: "Cote D'Ivoire", value: "COTE D'IVOIRE" },
    { label: "Croatia", value: "CROATIA" },
    { label: "Cuba", value: "CUBA" },
    { label: "Curacao", value: "CURACAO" },
    { label: "Cyprus", value: "CYPRUS" },
    { label: "Czech Republic", value: "CZECH REPUBLIC" },
    { label: "Denmark", value: "DENMARK" },
    { label: "Djibouti", value: "DJIBOUTI" },
    { label: "Dominica", value: "DOMINICA" },
    { label: "Dominican Republic", value: "DOMINICAN REPUBLIC" },
    { label: "Ecuador", value: "ECUADOR" },
    { label: "Egypt", value: "EGYPT" },
    { label: "El Salvador", value: "EL SALVADOR" },
    { label: "Equatorial Guinea", value: "EQUATORIAL GUINEA" },
    { label: "Eritrea", value: "ERITREA" },
    { label: "Estonia", value: "ESTONIA" },
    { label: "Ethiopia", value: "ETHIOPIA" },
    { label: "Falkland Islands (Malvinas)", value: "FALKLAND ISLANDS (MALVINAS)" },
    { label: "Faroe Islands", value: "FAROE ISLANDS" },
    { label: "Fiji", value: "FIJI" },
    { label: "Finland", value: "FINLAND" },
    { label: "France", value: "FRANCE" },
    { label: "French Guiana", value: "FRENCH GUIANA" },
    { label: "French Polynesia", value: "FRENCH POLYNESIA" },
    { label: "French Southern Territories", value: "FRENCH SOUTHERN TERRITORIES" },
    { label: "Gabon", value: "GABON" },
    { label: "Gambia", value: "GAMBIA" },
    { label: "Georgia", value: "GEORGIA" },
    { label: "Germany", value: "GERMANY" },
    { label: "Ghana", value: "GHANA" },
    { label: "Gibraltar", value: "GIBRALTAR" },
    { label: "Greece", value: "GREECE" },
    { label: "Greenland", value: "GREENLAND" },
    { label: "Grenada", value: "GRENADA" },
    { label: "Guadeloupe", value: "GUADELOUPE" },
    { label: "Guam", value: "GUAM" },
    { label: "Guatemala", value: "GUATEMALA" },
    { label: "Guernsey", value: "GUERNSEY" },
    { label: "Guinea", value: "GUINEA" },
    { label: "Guinea-Bissau", value: "GUINEA-BISSAU" },
    { label: "Guyana", value: "GUYANA" },
    { label: "Haiti", value: "HAITI" },
    { label: "Heard Island and Mcdonald Islands", value: "HEARD ISLAND AND MCDONALD ISLANDS" },
    { label: "Holy See (Vatican City State)", value: "HOLY SEE (VATICAN CITY STATE)" },
    { label: "Honduras", value: "HONDURAS" },
    { label: "Hong Kong", value: "HONG KONG" },
    { label: "Hungary", value: "HUNGARY" },
    { label: "Iceland", value: "ICELAND" },
    { label: "Indonesia", value: "INDONESIA" },
    { label: "Iran, Islamic Republic of", value: "IRAN, ISLAMIC REPUBLIC OF" },
    { label: "Iraq", value: "IRAQ" },
    { label: "Ireland", value: "IRELAND" },
    { label: "Isle of Man", value: "ISLE OF MAN" },
    { label: "Israel", value: "ISRAEL" },
    { label: "Italy", value: "ITALY" },
    { label: "Jamaica", value: "JAMAICA" },
    { label: "Japan", value: "JAPAN" },
    { label: "Jersey", value: "JERSEY" },
    { label: "Jordan", value: "JORDAN" },
    { label: "Kazakhstan", value: "KAZAKHSTAN" },
    { label: "Kenya", value: "KENYA" },
    { label: "Kiribati", value: "KIRIBATI" },
    { label: "Korea, Democratic People's Republic of", value: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" },
    { label: "Korea, Republic of", value: "KOREA, REPUBLIC OF" },
    { label: "Kosovo", value: "KOSOVO" },
    { label: "Kuwait", value: "KUWAIT" },
    { label: "Kyrgyzstan", value: "KYRGYZSTAN" },
    { label: "Lao People's Democratic Republic", value: "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
    { label: "Latvia", value: "LATVIA" },
    { label: "Lebanon", value: "LEBANON" },
    { label: "Lesotho", value: "LESOTHO" },
    { label: "Liberia", value: "LIBERIA" },
    { label: "Libyan Arab Jamahiriya", value: "LIBYAN ARAB JAMAHIRIYA" },
    { label: "Liechtenstein", value: "LIECHTENSTEIN" },
    { label: "Lithuania", value: "LITHUANIA" },
    { label: "Luxembourg", value: "LUXEMBOURG" },
    { label: "Macao", value: "MACAO" },
    { label: "Macedonia, the Former Yugoslav Republic of", value: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF" },
    { label: "Madagascar", value: "MADAGASCAR" },
    { label: "Malawi", value: "MALAWI" },
    { label: "Malaysia", value: "MALAYSIA" },
    { label: "Maldives", value: "MALDIVES" },
    { label: "Mali", value: "MALI" },
    { label: "Malta", value: "MALTA" },
    { label: "Marshall Islands", value: "MARSHALL ISLANDS" },
    { label: "Martinique", value: "MARTINIQUE" },
    { label: "Mauritania", value: "MAURITANIA" },
    { label: "Mauritius", value: "MAURITIUS" },
    { label: "Mayotte", value: "MAYOTTE" },
    { label: "Mexico", value: "MEXICO" },
    { label: "Micronesia, Federated States of", value: "MICRONESIA, FEDERATED STATES OF" },
    { label: "Moldova, Republic of", value: "MOLDOVA, REPUBLIC OF" },
    { label: "Monaco", value: "MONACO" },
    { label: "Mongolia", value: "MONGOLIA" },
    { label: "Montenegro", value: "MONTENEGRO" },
    { label: "Montserrat", value: "MONTSERRAT" },
    { label: "Morocco", value: "MOROCCO" },
    { label: "Mozambique", value: "MOZAMBIQUE" },
    { label: "Myanmar", value: "MYANMAR" },
    { label: "Namibia", value: "NAMIBIA" },
    { label: "Nauru", value: "NAURU" },
    { label: "Nepal", value: "NEPAL" },
    { label: "Netherlands", value: "NETHERLANDS" },
    { label: "Netherlands Antilles", value: "NETHERLANDS ANTILLES" },
    { label: "New Caledonia", value: "NEW CALEDONIA" },
    { label: "New Zealand", value: "NEW ZEALAND" },
    { label: "Nicaragua", value: "NICARAGUA" },
    { label: "Niger", value: "NIGER" },
    { label: "Nigeria", value: "NIGERIA" },
    { label: "Niue", value: "NIUE" },
    { label: "Norfolk Island", value: "NORFOLK ISLAND" },
    { label: "Northern Mariana Islands", value: "NORTHERN MARIANA ISLANDS" },
    { label: "Norway", value: "NORWAY" },
    { label: "Oman", value: "OMAN" },
    { label: "Pakistan", value: "PAKISTAN" },
    { label: "Palau", value: "PALAU" },
    { label: "Palestinian Territory, Occupied", value: "PALESTINIAN TERRITORY, OCCUPIED" },
    { label: "Panama", value: "PANAMA" },
    { label: "Papua New Guinea", value: "PAPUA NEW GUINEA" },
    { label: "Paraguay", value: "PARAGUAY" },
    { label: "Peru", value: "PERU" },
    { label: "Philippines", value: "PHILIPPINES" },
    { label: "Pitcairn", value: "PITCAIRN" },
    { label: "Poland", value: "POLAND" },
    { label: "Portugal", value: "PORTUGAL" },
    { label: "Puerto Rico", value: "PUERTO RICO" },
    { label: "Qatar", value: "QATAR" },
    { label: "Reunion", value: "REUNION" },
    { label: "Romania", value: "ROMANIA" },
    { label: "Russian Federation", value: "RUSSIAN FEDERATION" },
    { label: "Rwanda", value: "RWANDA" },
    { label: "Saint Barthelemy", value: "SAINT BARTHELEMY" },
    { label: "Saint Helena", value: "SAINT HELENA" },
    { label: "Saint Kitts and Nevis", value: "SAINT KITTS AND NEVIS" },
    { label: "Saint Lucia", value: "SAINT LUCIA" },
    { label: "Saint Martin", value: "SAINT MARTIN" },
    { label: "Saint Pierre and Miquelon", value: "SAINT PIERRE AND MIQUELON" },
    { label: "Saint Vincent and the Grenadines", value: "SAINT VINCENT AND THE GRENADINES" },
    { label: "Samoa", value: "SAMOA" },
    { label: "San Marino", value: "SAN MARINO" },
    { label: "Sao Tome and Principe", value: "SAO TOME AND PRINCIPE" },
    { label: "Saudi Arabia", value: "SAUDI ARABIA" },
    { label: "Senegal", value: "SENEGAL" },
    { label: "Serbia", value: "SERBIA" },
    { label: "Seychelles", value: "SEYCHELLES" },
    { label: "Sierra Leone", value: "SIERRA LEONE" },
    { label: "Singapore", value: "SINGAPORE" },
    { label: "Sint Maarten", value: "SINT MAARTEN" },
    { label: "Slovakia", value: "SLOVAKIA" },
    { label: "Slovenia", value: "SLOVENIA" },
    { label: "Solomon Islands", value: "SOLOMON ISLANDS" },
    { label: "Somalia", value: "SOMALIA" },
    { label: "South Africa", value: "SOUTH AFRICA" },
    { label: "South Georgia and the South Sandwich Islands", value: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" },
    { label: "South Sudan", value: "SOUTH SUDAN" },
    { label: "Spain", value: "SPAIN" },
    { label: "Sri Lanka", value: "SRI LANKA" },
    { label: "Sudan", value: "SUDAN" },
    { label: "Suriname", value: "SURINAME" },
    { label: "Svalbard and Jan Mayen", value: "SVALBARD AND JAN MAYEN" },
    { label: "Swaziland", value: "SWAZILAND" },
    { label: "Sweden", value: "SWEDEN" },
    { label: "Switzerland", value: "SWITZERLAND" },
    { label: "Syrian Arab Republic", value: "SYRIAN ARAB REPUBLIC" },
    { label: "Taiwan, Province of China", value: "TAIWAN, PROVINCE OF CHINA" },
    { label: "Tajikistan", value: "TAJIKISTAN" },
    { label: "Tanzania, United Republic of", value: "TANZANIA, UNITED REPUBLIC OF" },
    { label: "Thailand", value: "THAILAND" },
    { label: "Timor-Leste", value: "TIMOR-LESTE" },
    { label: "Togo", value: "TOGO" },
    { label: "Tokelau", value: "TOKELAU" },
    { label: "Tonga", value: "TONGA" },
    { label: "Trinidad and Tobago", value: "TRINIDAD AND TOBAGO" },
    { label: "Tunisia", value: "TUNISIA" },
    { label: "Turkey", value: "TURKEY" },
    { label: "Turkmenistan", value: "TURKMENISTAN" },
    { label: "Turks and Caicos Islands", value: "TURKS AND CAICOS ISLANDS" },
    { label: "Tuvalu", value: "TUVALU" },
    { label: "Uganda", value: "UGANDA" },
    { label: "Ukraine", value: "UKRAINE" },
    { label: "United Arab Emirates", value: "UNITED ARAB EMIRATES" },
    { label: "United Kingdom", value: "UNITED KINGDOM" },
    { label: "United States", value: "UNITED STATES" },
    { label: "United States Minor Outlying Islands", value: "UNITED STATES MINOR OUTLYING ISLANDS" },
    { label: "Uruguay", value: "URUGUAY" },
    { label: "Uzbekistan", value: "UZBEKISTAN" },
    { label: "Vanuatu", value: "VANUATU" },
    { label: "Venezuela", value: "VENEZUELA" },
    { label: "Viet Nam", value: "VIET NAM" },
    { label: "Virgin Islands, British", value: "VIRGIN ISLANDS, BRITISH" },
    { label: "Virgin Islands, U.s.", value: "VIRGIN ISLANDS, U.S." },
    { label: "Wallis and Futuna", value: "WALLIS AND FUTUNA" },
    { label: "Western Sahara", value: "WESTERN SAHARA" },
    { label: "Yemen", value: "YEMEN" },
    { label: "Zambia", value: "ZAMBIA" },
    { label: "Zimbabwe", value: "ZIMBABWE" },
];

export default COUNTRIES;
