export const gstStateCodeOptions = [
    { label: 'Andaman & Nicobar Islands', value: '35' },
    { label: 'Andhra Pradesh', value: '28' },
    { label: 'Andhra Pradesh (New)', value: '37' },
    { label: 'Arunachal Pradesh', value: '12' },
    { label: 'Assam', value: '18' },
    { label: 'Bihar', value: '10' },
    { label: 'Centre Jurisdiction / Non-Resident Taxable Person (NRTP)', value: '99' },
    { label: 'Chandigarh', value: '04' },
    { label: 'Chhattisgarh', value: '22' },
    { label: 'Dadra & Nagar Haveli and Daman & Diu', value: '26' },
    { label: 'Delhi', value: '07' },
    { label: 'Goa', value: '30' },
    { label: 'Gujarat', value: '24' },
    { label: 'Haryana', value: '06' },
    { label: 'Himachal Pradesh', value: '02' },
    { label: 'Jammu & Kashmir', value: '01' },
    { label: 'Jharkhand', value: '20' },
    { label: 'Karnataka', value: '29' },
    { label: 'Kerala', value: '32' },
    { label: 'Ladakh', value: '38' },
    { label: 'Lakshadweep', value: '31' },
    { label: 'Madhya Pradesh', value: '23' },
    { label: 'Maharashtra', value: '27' },
    { label: 'Manipur', value: '14' },
    { label: 'Meghalaya', value: '17' },
    { label: 'Mizoram', value: '15' },
    { label: 'Nagaland', value: '13' },
    { label: 'Odisha', value: '21' },
    { label: 'Other Territory', value: '97' },
    { label: 'Puducherry', value: '34' },
    { label: 'Punjab', value: '03' },
    { label: 'Rajasthan', value: '08' },
    { label: 'Sikkim', value: '11' },
    { label: 'Tamil Nadu', value: '33' },
    { label: 'Telangana', value: '36' },
    { label: 'Tripura', value: '16' },
    { label: 'Uttar Pradesh', value: '09' },
    { label: 'Uttarakhand', value: '05' },
    { label: 'West Bengal', value: '19' },
];
